### ISSUE TITLE
Block Limit may be exceeded

### ISSUE THREAD

**Issue by solaris007** [adobe/spacecat-api-service#176]
Using the `get sites` command may result in exceeding Slack's block limit:
```
inv.functionName:/spacecat-services/api-service/v1inv.invocationId:5ed1e44b-79bc-41c3-8bab-35e8d964e0aatimestamp:2024-02-23T14:05:01.652Zlevel:errorlogStream:2024/02/23/[595]54ee03b0b37649aaa77cb95f05879912message:Error: An API error occurred: invalid_blocks
at platformErrorFromResult (/var/task/index.js:27247:33)
at WebClient.apiCall (/var/task/index.js:26625:56)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async wrappedFunction (/var/task/index.js:95675:5)
at async sendMessageBlocks (/var/task/index.js:95571:3)
at async Object.handleExecution (/var/task/index.js:94527:7)
at async onAppMention (/var/task/index.js:95106:7)
at async Array.<anonymous> (/var/task/index.js:21449:9)
at async Array.onlyEvents (/var/task/index.js:21277:5)
at async Promise.allSettled (index 1) {
code: 'slack_webapi_platform_error',
data: {
ok: false,
error: 'invalid_blocks',
errors: [
'no more than 25 items allowed [json-pointer:/blocks/1/elements]'
],
response_metadata: { messages: [Array], scopes: [Array], acceptedScopes: [Array] }
}
}
```

we should find a way to have the slack command response adhere to those limits for long responses.

**Comment by ekremney** [comment]
closing as https://github.com/adobe/spacecat-api-service/pull/214 is merged
